name: tutorial
dependencies:
- backports_abc=0.4=py27_0
- cycler=0.9.0=py27_0
- decorator=4.0.6=py27_0
- ipykernel=4.2.2=py27_0
- ipython=4.0.3=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.0=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.0.3=py27_0
- jupyter_core=4.0.6=py27_0
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.0=np110py27_0
- mistune=0.7.1=py27_0
- msvc_runtime=1.0.1=vc9_0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.1.0=py27_0
- numpy=1.10.1=py27_0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- pickleshare=0.5=py27_0
- pip=8.0.2=py27_0
- pygments=2.1=py27_0
- pyreadline=2.1=py27_0
- python=2.7.11=2
- pyzmq=15.2.0=py27_0
- scikit-learn=0.17=np110py27_1
- seaborn=0.6.0=np110py27_0
- setuptools=19.6.2=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- ssl_match_hostname=3.4.0.2=py27_0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- wheel=0.26.0=py27_1
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - pexpect==4.0.1

